name: Execute Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Command to execute"
        required: true
        default: "echo Hello, GitHub Actions!"

jobs:
  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Print run ID
        run: echo "Run ID ${{ github.event.inputs.run_id }}"

      - name: Run command
        run: ${{ github.event.inputs.command }}
