name: Execute Command

on:
  workflow_dispatch:
jobs:
  run_command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: ${{ github.event.inputs.run_id }}
        run: echo "run_id:${{ github.event.inputs.run_id }}"

      - name: Run command
        run: ${{ github.event.inputs.command }}
